# Generated by Django 3.1.4 on 2020-12-27 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafe_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='meal',
            name='category',
            field=models.CharField(choices=[('BRE', 'Breakfast'), ('SAL', 'Salad'), ('BEV', 'Beverages')], default='BEV', max_length=3),
        ),
    ]
